ci: parallelize build projects and provide parameter for build output
Signed-off-by: Jonathan Basniak <740416+gm112@users.noreply.github.com>

diff --git a/.github/actions/build-pnpm-workspace/action.yml b/.github/actions/build-pnpm-workspace/action.yml
--- a/.github/actions/build-pnpm-workspace/action.yml
+++ b/.github/actions/build-pnpm-workspace/action.yml
@@ -13,6 +13,15 @@ inputs:
     description: 'Overwrite existing build artifacts'
     required: false
     default: 'false'
+  build-output-directory:
+    description: 'Directory to output build artifacts'
+    required: false
+    default: '.output'
+  upload-artifact-name:
+    description: 'Name of the artifact to upload'
+    required: false
+    default: 'build-artifacts'
+
 runs:
   using: 'composite'
   steps:
@@ -50,34 +59,33 @@ runs:
         echo "Installing dependencies"
         pnpm install --frozen-lockfile
 
-    - name: Validate Code Formatting
+    - name: Build Projects and Validate Code Formatting
       shell: bash
-      run: echo "Validating Code Formatting" && pnpm run --parallel lint
+      run: |
+        echo "Building Projects"
+        pnpm run --parallel build & build_pid=$!
 
-    - name: Build Projects
-      shell: bash
-      run: echo "Building Projects" && pnpm run --parallel build
+        echo "Validating Code Formatting"
+        pnpm run --parallel lint & lint_pid=$!
 
-    - name: Test Projects
-      shell: bash
-      run: echo "Testing Projects" && pnpm run --parallel test
+        echo "Testing Projects"
+        pnpm run --parallel test & test_pid=$!
 
-    # - name: Retrieve Build Artifacts
-    #   if: inputs.upload-build-artifacts == 'true'
-    #   shell: bash
-    #   run: |
-    #     echo "Grabbing Build Artifacts"
+        wait $build_pid; build_exit_code=$?
+        wait $lint_pid; lint_exit_code=$?
+        wait $test_pid; test_exit_code=$?
 
-    #     mkdir -p ./.output
-    #     # Move all .output directories in the projects/{project-name} directories in ./projects/, using the project folder name as a parent folder name in ./.output/.
-    #     find ./projects -mindepth 1 -maxdepth 1 -type d -exec bash -c 'mv "$1"/.output "$1"/../' {} \;
+        if [ $build_exit_code -ne 0 ] || [ $lint_exit_code -ne 0 ] || [ $test_exit_code -ne 0 ]; then
+          echo "Build, lint, or test failed. Exiting." >&2
+          exit 1
+        fi
 
     - name: Upload Build Artifacts
       if: inputs.upload-build-artifacts == 'true'
       uses: actions/upload-artifact@v4
       with:
-        name: build-artifacts
-        path: projects/**/.output/
+        name: ${{ inputs.upload-artifact-name }}
+        path: ${{ inputs.build-output-directory }}
         if-no-files-found: error
         overwrite: ${{ inputs.overwrite-build-artifacts }}
 
